### ISSUE TITLE
Testing, phase I

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#103]
The ticket will provide all the bugs/inconsistencies detected in the testing phase

- [x] url:  https://edu-hospice.herokuapp.com/#/preview/register  - the labels  of the first name and the last name  are inconsistent with the textboxs placeholders

- [x] url: https://edu-hospice.herokuapp.com/#/admin/course-list/course - the form buttons should have a margin, also they should placed on the right side

- [x] https://edu-hospice.herokuapp.com/#/preview/login - the login button should have a blue background, just like the other "positive action" buttons

**Comment by VlaDDraGu89** [comment]
Nice to have : another tab with all the courses available , while on student user 
url : https://edu-hospice.herokuapp.com/#/user/dashboard

**Comment by Adrian-Moldovan** [comment]
All good, beam me up on production, Scotty.
